-- MySQL Script generated by MySQL Workbench
-- Tue Dec  1 21:06:53 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema epam_cafe
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema epam_cafe
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `epam_cafe` DEFAULT CHARACTER SET utf8 ;
USE `epam_cafe` ;

-- -----------------------------------------------------
-- Table `epam_cafe`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `epam_cafe`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(50) NOT NULL,
  `password` VARCHAR(50) NOT NULL,
  `role` VARCHAR(20) NOT NULL DEFAULT 'USER',
  `money` DECIMAL(10,2) NOT NULL DEFAULT 0.0,
  `active` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `LOGIN_UNIQUE` (`login` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `epam_cafe`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `epam_cafe`.`order` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cost` DECIMAL(10,2) NOT NULL,
  `time` DATETIME NOT NULL,
  `active` TINYINT NOT NULL DEFAULT 1,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idORDER_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_order_user_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `epam_cafe`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `epam_cafe`.`dish`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `epam_cafe`.`dish` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `type` VARCHAR(50) NOT NULL,
  `cost` DOUBLE(10,2) NOT NULL,
  `image_ref` VARCHAR(100) NULL DEFAULT '../../static/images/not_found.png',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `product_id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `epam_cafe`.`order_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `epam_cafe`.`order_product` (
  `order_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  INDEX `fk_order_idx` (`order_id` ASC) VISIBLE,
  INDEX `fk_product_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_order`
    FOREIGN KEY (`order_id`)
    REFERENCES `epam_cafe`.`order` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_product`
    FOREIGN KEY (`product_id`)
    REFERENCES `epam_cafe`.`dish` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `epam_cafe`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `epam_cafe`.`comment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `text` VARCHAR(250) NOT NULL,
  `user_id` INT NOT NULL,
  `dish_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `comment_id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_user_id_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_product_id_idx` (`dish_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `epam_cafe`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_product_id`
    FOREIGN KEY (`dish_id`)
    REFERENCES `epam_cafe`.`dish` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
